select *from memberMEMBER create table member
(
    id bigint generated by default as identity,
    LoginId varchar(255),
    pw varchar(255),
    pwcheck varchar(255),
    nickname char(20),
    pnum char(10),
    certified char(7),
    primary key (id)
);